-- Initial schema. Generated by Lovable.
create table public.profiles (
  id uuid primary key default uuid_generate_v4(),
  email text not null,
  full_name text,
  created_at timestamptz default now()
);

-- no RLS enablement here.

create table public.posts (
  id uuid primary key default uuid_generate_v4(),
  author_id uuid references public.profiles(id),
  body text,
  created_at timestamptz default now()
);

alter table public.posts enable row level security;

create policy "anyone can read posts" on public.posts
  for select using (true);

create policy "authed can select profiles" on public.profiles
  for select using (auth.role() = 'authenticated');

create table public.secrets (
  id uuid primary key,
  value text
);
